media:
  - name: media
    label: Media
    input: src/media
    output: media
content:
  - name: impressum
    label: Impressum
    type: file
    path: src/pages/impressum.md
    fields:
      - name: layout
        type: string
        hidden: true
        default: "../layouts/Impressum.astro"
      - name: title
        label: Title
        type: string
      - name: content
        label: Content
        type: rich-text
  - name: datenschutz
    label: Datenschutz
    type: file
    path: src/pages/datenschutz.md
    fields:
      - name: layout
        type: string
        hidden: true
        default: "../layouts/Datenschutz.astro"
      - name: title
        label: Title
        type: string
      - name: content
        label: Content
        type: rich-text
components:
  richtext:
    label: Richtext
    type: object
    fields:
      - name: body
        label: Body
        type: rich-text