media:
  - name: media
    label: Media
    input: src/media
    output: media
content:
  - name: globals
    label: Global Settings
    type: file
    path: src/data/globals.json
    format: json
    fields:
      - name: siteTitle
        label: Site Title
        type: string
        required: true
      - name: siteDescription
        label: Site Description
        type: string
        required: true
      - name: siteImage
        label: Site Image (1200x630)
        type: image
        required: true
      - name: footerContent
        label: Footer Content
        type: rich-text
        required: true
      - name: footerLogo
        label: Footer Logo (linked to Home Page)
        type: image
        required: true
      - name: footerLegal
        label: Copyright and Links to Legal Pages
        type: rich-text
        required: true
      - name: footerLinkFacebook
        label: Link to Facebook
        type: string
        required: true
      - name: footerLinkInstagram
        label: Link to Instagram
        type: string
        required: true
  - name: generic
    label: Generic Pages
    type: collection
    path: src/content/pagesGeneric
    filename: '{primary}.md'
    view:
      fields: [ slug, title ]
    fields:
      - name: slug
        label: Slug (Meta)
        type: string
        required: true
      - name: title
        label: Title (Meta)
        type: string
        required: true
      - name: sections
        label: Page Sections
        type: object
        list:
          collapsible:
            summary: 'Section'
        fields:
          - name: modules
            label: Modules
            type: block
            blockKey: type
            list:
              collapsible:
                summary: 'Module {index}'
            blocks:
              - name: title
                label: Title (Heading 1)
                component: title
              - name: richText
                label: Rich-Text
                component: richText
  - name: '404'
    label: 404 Page
    type: file
    path: src/pages/404.md
    fields:
      - name: layout
        type: string
        default: '../layouts/Page404.astro'
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: subline
        label: Subline
        type: string
        required: true
      - name: linkText
        label: Back Home Link Text
        type: string
        required: true
components:
  title:
    label: Title
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
  richText:
    label: Rich-Text
    type: object
    fields:
      - name: content
        label: Content
        type: rich-text
        required: true