media:
  - name: media
    label: Media
    input: src/media
    output: media
content:
  - name: generic
    label: Generic
    type: collection
    path: src/pages
    filename: '{primary}.md'
    fields:
      - name: slug
        type: string
      - name: layout
        type: string
        default: '../layouts/Generic.astro'
        hidden: true
      - name: title
        label: Title
        type: string
      - name: content
        label: Content
        type: rich-text
      - name: image
        label: Image
        type: image
